python -u contrastive_pretraining.py --data_dir /l/users/salwa.khatib/penet/data/ \
                                    --name UnFreezePeNet100EpochsNoSubsegmental \
                                    --unfreeze_penet True \
                                    --num_epochs 100 \
                                    --dataset pe \
                                    --use_pretrained True \
                                    --ckpt_path data-dir/penet_best.pth.tar \
                                    --clip_bs 4 \
                                    --resume_training False \
                                    --penet_resume_path data-dir/penet_best.pth.tar \
                                    --img_resume_path checkpoints/clip400Epochs/epoch4-pretrained_img_model.pt \
                                    --ehr_resume_path checkpoints/clip400Epochs/epoch4-pretrained_ehr_model.pt \
